In [1]:
import pandas as pd
import numpy as np
import torch
from torch import nn

In [425]:
data = pd.read_excel("parsis_new.xlsx")

In [426]:
data.head()

SL_CODE          DBT        CRD  MAIN_CODE          SUM
0  501073102     54898837          0     600400     54898837
1  501073210   6586589538          0     613500   6586589538
2  501073211  52724428135          0     613300  52724428135
3  501080401   7227600967          0     515400   7227600967
4  401111370            0  129950000     508800   -129950000

In [427]:
data = data.drop(["SL_CODE", "MAIN_CODE"], axis=1)

In [428]:
input_data = data.drop('SUM', axis=1)

In [429]:
output_data = data['SUM']

In [430]:
input_data = torch.tensor(input_data.values).type(torch.float32)
output_data = torch.tensor(output_data).type(torch.float32)

In [431]:
output_data = output_data.unsqueeze(dim=1)

In [336]:
class LinearRegression(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(2, 10)
        self.layer2 = nn.Linear(10, 10)
        self.layer3 = nn.Linear(10, 1)
        self.relu = nn.ReLU()
        
    def forward(self, x):
        x = self.layer3(self.relu(self.layer2(self.relu(self.layer1(x)))))
        return x

In [337]:
model = LinearRegression()

In [360]:
loss_fn = nn.L1Loss()

optimizer = torch.optim.Adam(params=model.parameters(), lr=0.000000001)

In [361]:
epochs = 5000
for epoch in range(epochs):
    model.train()
    X_preds = model(input_data)
    loss = loss_fn(output_data, X_preds)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print(f"Epoch: {epoch} | Loss: {loss}")

Epoch: 0 | Loss: 13757.4267578125
Epoch: 100 | Loss: 13757.4267578125
Epoch: 200 | Loss: 13757.4267578125
Epoch: 300 | Loss: 13757.4267578125
Epoch: 400 | Loss: 13757.4267578125
Epoch: 500 | Loss: 13757.4267578125
Epoch: 600 | Loss: 13757.4267578125
Epoch: 700 | Loss: 13757.4267578125
Epoch: 800 | Loss: 13757.4267578125
Epoch: 900 | Loss: 13757.4267578125
Epoch: 1000 | Loss: 13757.4267578125
Epoch: 1100 | Loss: 13757.4267578125
Epoch: 1200 | Loss: 13757.4267578125
Epoch: 1300 | Loss: 13757.4267578125
Epoch: 1400 | Loss: 13757.4267578125
Epoch: 1500 | Loss: 13757.4267578125
Epoch: 1600 | Loss: 13757.4267578125
Epoch: 1700 | Loss: 13757.4267578125
Epoch: 1800 | Loss: 13757.4267578125
Epoch: 1900 | Loss: 13757.4267578125
Epoch: 2000 | Loss: 13757.4267578125
Epoch: 2100 | Loss: 13757.4267578125
Epoch: 2200 | Loss: 13757.4267578125
Epoch: 2300 | Loss: 13757.4267578125
Epoch: 2400 | Loss: 13757.4267578125
Epoch: 2500 | Loss: 13757.4267578125
Epoch: 2600 | Loss: 13757.4267578125
Epoch: 2700 |

In [362]:
sample = torch.tensor([78000000, 4000000], dtype=torch.float32)
test = model(sample)
test

tensor([74590840.], grad_fn=<AddBackward0>)

In [432]:
class LinearRegressionModelV2(nn.Module):
    def __init__(self):
        super().__init__()
        # Use nn.Linear() for creating the model parameters / also called: linear transform, probing layer, fully connected layer, dense layer
        self.linear_layer = nn.Linear(in_features=2,
                                      out_features=1)
    
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.linear_layer(x)

# Set the manual seed
torch.manual_seed(42)
model_1 = LinearRegressionModelV2()
model_1, model_1.state_dict()

(LinearRegressionModelV2(
   (linear_layer): Linear(in_features=2, out_features=1, bias=True)
 ),
 OrderedDict([('linear_layer.weight', tensor([[0.5406, 0.5869]])),
              ('linear_layer.bias', tensor([-0.1657]))]))

In [450]:
# Setup loss function
loss_fn = nn.L1Loss() # same as MAE

# Setup our optimizer
optimizer = torch.optim.Adam(params=model_1.parameters(), 
                            lr=0.0000001)

In [451]:
torch.manual_seed(42)

epochs = 3000

# Put data on the target device (device agnostic code for data) 
# X_train = X_train.to(device)
# y_train = y_train.to(device)
# X_test = X_test.to(device)
# y_test = y_test.to(device)

for epoch in range(epochs):
    model_1.train()

    # 1. Forward pass
    y_pred = model_1(input_data)

    # 2. Calculate the loss
    loss = loss_fn(y_pred, output_data)

    # 3. Optimizer zero grad
    optimizer.zero_grad()

    # 4. Perform backpropagation
    loss.backward()

    # 5. Optimizer step
    optimizer.step()

    ### Testing
#     model_1.eval()
#     with torch.inference_mode():
#     test_pred = model_1(X_test)

#     test_loss = loss_fn(test_pred, y_test)

    # Print out what's happening
    if epoch % 100 == 0: 
#     print(f"Epoch: {epoch} | Loss: {loss} | Test loss: {test_loss}")
        print(f"Epoch: {epoch} | Loss: {loss}")

Epoch: 0 | Loss: 62907.5390625
Epoch: 100 | Loss: 0.09427911043167114
Epoch: 200 | Loss: 0.0942787304520607
Epoch: 300 | Loss: 0.0942784771323204
Epoch: 400 | Loss: 0.09427794069051743
Epoch: 500 | Loss: 0.09427718073129654
Epoch: 600 | Loss: 0.09427664428949356
Epoch: 700 | Loss: 0.09427616000175476
Epoch: 800 | Loss: 0.09427555650472641
Epoch: 900 | Loss: 0.09427501261234283
Epoch: 1000 | Loss: 0.09414659440517426
Epoch: 1100 | Loss: 0.09414602816104889
Epoch: 1200 | Loss: 0.09414554387331009
Epoch: 1300 | Loss: 0.09414492547512054
Epoch: 1400 | Loss: 0.09414439648389816
Epoch: 1500 | Loss: 0.09414364397525787
Epoch: 1600 | Loss: 0.09414315223693848
Epoch: 1700 | Loss: 0.0941426157951355
Epoch: 1800 | Loss: 0.09414200484752655
Epoch: 1900 | Loss: 0.09414144605398178
Epoch: 2000 | Loss: 0.09413839131593704
Epoch: 2100 | Loss: 0.09413789957761765
Epoch: 2200 | Loss: 0.09413736313581467
Epoch: 2300 | Loss: 0.09413676708936691
Epoch: 2400 | Loss: 0.09413623064756393
Epoch: 2500 | Loss: 0

In [452]:
sample = torch.tensor([155000000, 100000000], dtype=torch.float32)
test = model_1(sample)
test

tensor([55000000.], grad_fn=<AddBackward0>)

In [66]:
data_new = pd.read_excel("parsis_new.xlsx")

In [67]:
data_new.head()
input_new = data_new.drop('SUM', axis=1)
input_new.head()

SL_CODE          DBT        CRD  MAIN_CODE
0  501073102     54898837          0     600400
1  501073210   6586589538          0     613500
2  501073211  52724428135          0     613300
3  501080401   7227600967          0     515400
4  401111370            0  129950000     508800

In [6]:
input_new = torch.tensor(input_new.values).type(torch.float32)

In [5]:
class LinearRegressionModelV3(nn.Module):
    def __init__(self):
        super().__init__()
        # Use nn.Linear() for creating the model parameters / also called: linear transform, probing layer, fully connected layer, dense layer
        self.linear_layer = nn.Linear(in_features=4,
                                      out_features=1)
    
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.linear_layer(x)

# Set the manual seed
torch.manual_seed(42)
model_2 = LinearRegressionModelV3()
model_2, model_2.state_dict()

(LinearRegressionModelV3(
   (linear_layer): Linear(in_features=4, out_features=1, bias=True)
 ),
 OrderedDict([('linear_layer.weight',
               tensor([[ 0.3823,  0.4150, -0.1171,  0.4593]])),
              ('linear_layer.bias', tensor([-0.1096]))]))

In [493]:
# Setup loss function
loss_fn = nn.L1Loss() # same as MAE

# Setup our optimizer
optimizer = torch.optim.Adam(params=model_2.parameters(), 
                            lr=0.00000000001)

In [494]:
torch.manual_seed(42)

epochs = 3000

# Put data on the target device (device agnostic code for data) 
# X_train = X_train.to(device)
# y_train = y_train.to(device)
# X_test = X_test.to(device)
# y_test = y_test.to(device)

for epoch in range(epochs):
    model_2.train()

    # 1. Forward pass
    y_pred = model_2(input_new)

    # 2. Calculate the loss
    loss = loss_fn(y_pred, output_data)

    # 3. Optimizer zero grad
    optimizer.zero_grad()

    # 4. Perform backpropagation
    loss.backward()

    # 5. Optimizer step
    optimizer.step()

    ### Testing
#     model_1.eval()
#     with torch.inference_mode():
#     test_pred = model_1(X_test)

#     test_loss = loss_fn(test_pred, y_test)

    # Print out what's happening
    if epoch % 100 == 0: 
#     print(f"Epoch: {epoch} | Loss: {loss} | Test loss: {test_loss}")
        print(f"Epoch: {epoch} | Loss: {loss}")

Epoch: 0 | Loss: 0.04439706727862358
Epoch: 100 | Loss: 0.04432680457830429
Epoch: 200 | Loss: 0.0439237505197525
Epoch: 300 | Loss: 0.04390479251742363
Epoch: 400 | Loss: 0.04390447214245796
Epoch: 500 | Loss: 0.04391338303685188
Epoch: 600 | Loss: 0.04389079287648201
Epoch: 700 | Loss: 0.04390574246644974
Epoch: 800 | Loss: 0.04428818076848984
Epoch: 900 | Loss: 0.04399435222148895
Epoch: 1000 | Loss: 0.043931540101766586
Epoch: 1100 | Loss: 0.043956954032182693
Epoch: 1200 | Loss: 0.043917495757341385
Epoch: 1300 | Loss: 0.04391724616289139
Epoch: 1400 | Loss: 0.04396079480648041
Epoch: 1500 | Loss: 0.04402059316635132
Epoch: 1600 | Loss: 0.04387694224715233
Epoch: 1700 | Loss: 0.043930135667324066
Epoch: 1800 | Loss: 0.04396044462919235
Epoch: 1900 | Loss: 0.04392709955573082
Epoch: 2000 | Loss: 0.043885424733161926
Epoch: 2100 | Loss: 0.043905068188905716
Epoch: 2200 | Loss: 0.04393460229039192
Epoch: 2300 | Loss: 0.04430156946182251
Epoch: 2400 | Loss: 0.043989408761262894
Epoch:

In [498]:
data_new.groupby('MAIN_CODE').sum()

SL_CODE              DBT             CRD              SUM
MAIN_CODE                                                               
0           2854678023    1761330573356     30765754013    1730564819343
100500       303060306      11390149614               0      11390149614
100700       101040101         39579000               0         39579000
101900       104010101     249389455013               0     249389455013
102100       104050101    2904644812613               0    2904644812613
...                ...              ...             ...              ...
12000012   27707320666  139027072006588  27793993907603  111233078098985
81500001     604020101    3358692191875               0    3358692191875
81500002    1913040503     905470836866    103537443857     801933393009
81500003     604050201      86420706493               0      86420706493
81500004     604060201     105536693552               0     105536693552

[184 rows x 4 columns]

In [8]:
MODEL_SAVE_PATH = "./01_pytorch_model_2.pth"
torch.save(obj=model_2.state_dict(),
           f=MODEL_SAVE_PATH) 

In [9]:
loaded_model_1 = LinearRegressionModelV3()
loaded_model_1.load_state_dict(torch.load(MODEL_SAVE_PATH))

<All keys matched successfully>

In [10]:
loaded_model_1.state_dict()

OrderedDict([('linear_layer.weight',
              tensor([[ 8.4879e-10,  1.0000e+00, -1.0000e+00,  5.1590e-08]])),
             ('linear_layer.bias', tensor([-0.7144]))])

In [11]:
model_2.state_dict()

OrderedDict([('linear_layer.weight',
              tensor([[ 0.3823,  0.4150, -0.1171,  0.4593]])),
             ('linear_layer.bias', tensor([-0.1096]))])

In [15]:
output_test = loaded_model_1(input_new[0])
output_test

tensor([54898836.], grad_fn=<AddBackward0>)

In [16]:
data_new.head()

SL_CODE          DBT        CRD  MAIN_CODE          SUM
0  501073102     54898837          0     600400     54898837
1  501073210   6586589538          0     613500   6586589538
2  501073211  52724428135          0     613300  52724428135
3  501080401   7227600967          0     515400   7227600967
4  401111370            0  129950000     508800   -129950000

In [24]:
input_numpy = input_new.numpy()

In [34]:
input_numpy_dataframe = pd.DataFrame(input_numpy)

In [35]:
input_numpy_dataframe.head()

0             1            2         3
0  501073088.0  5.489884e+07          0.0  600400.0
1  501073216.0  6.586590e+09          0.0  613500.0
2  501073216.0  5.272443e+10          0.0  613300.0
3  501080416.0  7.227601e+09          0.0  515400.0
4  401111360.0  0.000000e+00  129950000.0  508800.0

In [36]:
input_numpy_dataframe[input_numpy_dataframe[3]==600400]

0             1    2         3
0     501073088.0  5.489884e+07  0.0  600400.0
126   501020416.0  3.000000e+00  0.0  600400.0
285   501020192.0  5.261943e+08  0.0  600400.0
286   501020416.0  1.358900e+05  0.0  600400.0
422   501020192.0  1.727941e+12  0.0  600400.0
423   501020192.0  4.229421e+11  0.0  600400.0
724   501020192.0  7.095890e+09  0.0  600400.0
858   501020192.0  2.802392e+10  0.0  600400.0
859   501020416.0  5.456438e+06  0.0  600400.0
1191  501020128.0  1.397260e+11  0.0  600400.0

In [45]:
data_test = pd.read_excel('data5.xlsx')
data_test

401053404              0    914808778  501800
0    401053409              0   8922333039  501800
1    401053410              0      3930792  501800
2    116010203   128669417343            0  145400
3    210050104              0  85451896409  145400
4    116010204       60883560            0  145600
..         ...            ...          ...     ...
800  501072101  1593423852270            0  615200
801  501072101    75932000000            0  615200
802  501072501   750000000000            0  620200
803  501070101      572000000            0  625200
804  501070101    74219028543            0  625200

[805 rows x 4 columns]

In [47]:
data_64_t = torch.tensor(data_64.values).type(torch.float)

In [46]:
data_64 = data_test[data_test[501800]==600400]
data_64

401053404              0  914808778  501800
481  501020201  1233324957388          0  600400
482  501020414       45139401          0  600400
483  501020419       21086236          0  600400
583  501020422       24741943          0  600400
584  501020203       70205140          0  600400
798  501020201   975165000000          0  600400

In [54]:
with torch.no_grad():
    natije = loaded_model_1(data_64_t)

In [55]:
natije

tensor([[1.2333e+12],
        [4.5139e+07],
        [2.1086e+07],
        [2.4742e+07],
        [7.0205e+07],
        [9.7516e+11]])

In [56]:
torch.sum(natije)

tensor(2.2087e+12)

In [57]:
out_put_numpy = natije.numpy()

In [58]:
output_df = pd.DataFrame(out_put_numpy)
output_df

0
0  1.233325e+12
1  4.513940e+07
2  2.108624e+07
3  2.474194e+07
4  7.020514e+07
5  9.751650e+11

In [60]:
import numpy as np

In [61]:
np.sum(output_df[0])

2208651300000.0

In [65]:
print(output_df[:3])

              0
0  1.233325e+12
1  4.513940e+07
2  2.108624e+07


In [68]:
mapinfo = pd.read_excel("MAPINFO.xlsx")

In [69]:
mapinfo.head()

SL_CODE          DBT        CRD  MAIN_CODE          SUM
0  501073102     54898837          0     600400     54898837
1  501073210   6586589538          0     613500   6586589538
2  501073211  52724428135          0     613300  52724428135
3  501080401   7227600967          0     515400   7227600967
4  401111370            0  129950000     508800   -129950000

In [70]:
mapinfo_input = mapinfo.drop('SUM', axis=1)mapinfo['MAIN_CODE']

In [75]:
mapinfo_64 = mapinfo_input[mapinfo_input['MAIN_CODE']==600400]

In [76]:
mapinfo_input_t = torch.tensor(mapinfo_64.values).type(torch.float32)

In [77]:
mapinfo_input_t

tensor([[5.0107e+08, 5.4899e+07, 0.0000e+00, 6.0040e+05],
        [5.0102e+08, 3.0000e+00, 0.0000e+00, 6.0040e+05],
        [5.0102e+08, 5.2619e+08, 0.0000e+00, 6.0040e+05],
        [5.0102e+08, 1.3589e+05, 0.0000e+00, 6.0040e+05],
        [5.0102e+08, 1.7279e+12, 0.0000e+00, 6.0040e+05],
        [5.0102e+08, 7.0959e+09, 0.0000e+00, 6.0040e+05],
        [5.0102e+08, 2.8024e+10, 0.0000e+00, 6.0040e+05],
        [5.0102e+08, 5.4564e+06, 0.0000e+00, 6.0040e+05]])

In [82]:
with torch.no_grad():
    out_map = loaded_model_1(mapinfo_input_t)

In [93]:
out_map

tensor([[5.4899e+07],
        [2.7419e+00],
        [5.2619e+08],
        [1.3589e+05],
        [1.7279e+12],
        [7.0959e+09],
        [2.8024e+10],
        [5.4564e+06]])

In [94]:
out_map_Scaler = out_map.squeeze()

In [91]:
print(torch.sum(out_map).item())

1763647684608.0


In [103]:
data_7 = pd.read_excel("data7.xlsx")
out_7 = data_7["SUM"]
data_7 = data_7.drop('SUM', axis=1)

In [104]:
data_7_input = torch.tensor(data_7.values).type(torch.float32)

In [106]:
data_7_input

tensor([[5.0107e+08, 5.4899e+07, 0.0000e+00, 6.0040e+05],
        [5.0107e+08, 6.5866e+09, 0.0000e+00, 6.1350e+05],
        [5.0107e+08, 5.2724e+10, 0.0000e+00, 6.1330e+05],
        ...,
        [1.1109e+08, 5.5785e+12, 0.0000e+00, 1.2000e+07],
        [5.0104e+08, 0.0000e+00, 0.0000e+00, 6.0590e+05],
        [1.1814e+08, 0.0000e+00, 0.0000e+00, 1.3520e+06]])

In [109]:
with torch.no_grad():
    out_model = loaded_model_1(data_7_input)

In [110]:
out_model

tensor([[ 5.4899e+07],
        [ 6.5866e+09],
        [ 5.2724e+10],
        ...,
        [ 5.5785e+12],
        [-2.5784e-01],
        [-5.4435e-01]])

In [115]:
t_np = out_model.numpy() #convert to Numpy array
df = pd.DataFrame(t_np) #convert to a dataframe
df.to_csv("testfile.csv",index=False) #save to file

In [113]:
df = pd.read_csv("testfile")

In [120]:
df_main_code = mapinfo['MAIN_CODE']

In [125]:
df_merged = pd.concat([df, df_main_code], ignore_index=True, sort=False)

In [126]:
df_merged.head()

0
0  5.489884e+07
1  6.586590e+09
2  5.272443e+10
3  7.227601e+09
4 -1.299500e+08

In [134]:
class LinearRegressionModelV5(nn.Module):
    def __init__(self, input_features, output_features, hidden_units=8):
        super().__init__()
        # Use nn.Linear() for creating the model parameters / also called: linear transform, probing layer, fully connected layer, dense layer
        self.linear_layer = nn.Linear(in_features=input_features,
                                      out_features=output_features)
    
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.linear_layer(x)

# Set the manual seed
torch.manual_seed(42)
model_akhar = LinearRegressionModelV5(3, 1)
model_akhar, model_akhar.state_dict()

(LinearRegressionModelV5(
   (linear_layer): Linear(in_features=3, out_features=1, bias=True)
 ),
 OrderedDict([('linear_layer.weight', tensor([[ 0.4414,  0.4792, -0.1353]])),
              ('linear_layer.bias', tensor([0.5304]))]))

In [132]:
data_8 = pd.read_excel("data8.xlsx")

In [133]:
data_8.head()

sl  dbt          crd          sum
0  401052302    0    266275758   -266275758
1  401052303    0   4603539430  -4603539430
2  401052501    0   5532375073  -5532375073
3  401052502    0    735035629   -735035629
4  401052504    0  16103462695 -16103462695

In [135]:
input_data = data_8.drop('sum', axis=1)
output_data = data_8['sum']

In [136]:
input_data_t = torch.tensor(input_data.values).type(torch.float32)
output_data_t = torch.tensor(output_data).type(torch.float32)

In [139]:
input_data_t.size(), output_data_t.size()

(torch.Size([13001, 3]), torch.Size([13001]))

In [140]:
output_data_t = output_data_t.unsqueeze(dim=1)

In [175]:
loss_fn = nn.L1Loss() # same as MAE

# Setup our optimizer
optimizer = torch.optim.Adam(params=model_akhar.parameters(), 
                            lr=0.0000000001)

In [176]:
torch.manual_seed(42)

epochs = 1000

# Put data on the target device (device agnostic code for data) 
# X_train = X_train.to(device)
# y_train = y_train.to(device)
# X_test = X_test.to(device)
# y_test = y_test.to(device)

for epoch in range(epochs):
    model_akhar.train()

    # 1. Forward pass
    y_pred = model_akhar(input_data_t)

    # 2. Calculate the loss
    loss = loss_fn(y_pred, output_data_t)

    # 3. Optimizer zero grad
    optimizer.zero_grad()

    # 4. Perform backpropagation
    loss.backward()

    # 5. Optimizer step
    optimizer.step()

    ### Testing
#     model_1.eval()
#     with torch.inference_mode():
#     test_pred = model_1(X_test)

#     test_loss = loss_fn(test_pred, y_test)

    # Print out what's happening
    if epoch % 100 == 0: 
#     print(f"Epoch: {epoch} | Loss: {loss} | Test loss: {test_loss}")
        print(f"Epoch: {epoch} | Loss: {loss}")

Epoch: 0 | Loss: 0.01974686048924923
Epoch: 100 | Loss: 0.019217846915125847
Epoch: 200 | Loss: 0.019106173887848854
Epoch: 300 | Loss: 0.019117096439003944
Epoch: 400 | Loss: 0.01913115382194519
Epoch: 500 | Loss: 0.019080132246017456
Epoch: 600 | Loss: 0.019635938107967377
Epoch: 700 | Loss: 0.01973060332238674
Epoch: 800 | Loss: 0.019487446174025536
Epoch: 900 | Loss: 0.01972619816660881


In [177]:
test_input = pd.read_excel('data9.xlsx')
test_input

401052302           0    266275758
0     401052303           0   4603539430
1     401052501           0   5532375073
2     401052502           0    735035629
3     401052504           0  16103462695
4     401053001           0   6867785245
...         ...         ...          ...
5980  118073502  4039923081            0
5981  118073503  3565959756            0
5982  118073505   295273020            0
5983  118073506   265636878            0
5984  118073510           0            0

[5985 rows x 3 columns]

In [178]:
test_input_t = torch.tensor(test_input.values).type(torch.float32)
test_input_t

tensor([[4.0105e+08, 0.0000e+00, 4.6035e+09],
        [4.0105e+08, 0.0000e+00, 5.5324e+09],
        [4.0105e+08, 0.0000e+00, 7.3504e+08],
        ...,
        [1.1807e+08, 2.9527e+08, 0.0000e+00],
        [1.1807e+08, 2.6564e+08, 0.0000e+00],
        [1.1807e+08, 0.0000e+00, 0.0000e+00]])

In [181]:
with torch.no_grad():
    natije_akhar = model_akhar(test_input_t)

In [182]:
natije_akhar

tensor([[-4.6035e+09],
        [-5.5324e+09],
        [-7.3504e+08],
        ...,
        [ 2.9527e+08],
        [ 2.6564e+08],
        [ 1.6124e-01]])

In [183]:
t_np = natije_akhar.numpy() #convert to Numpy array
df = pd.DataFrame(t_np) #convert to a dataframe
df.to_csv("test_file2.csv",index=False) #save to file